{
 "title": "InfluxDB Internals",
 "description": "InfluxDB internal metrics display",
 "tags": [
  "InfluxDB",
  "Prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(influxdb_runtime_sys, job)"
   }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query Executor: Active Queries",
   "type": "singlestat",
   "description": "The number of active queries currently being handled.\n\nhttps://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/measurements-internal/",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_query_executor_queries_active{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Query Executor: Finished Queries",
   "type": "singlestat",
   "description": "The number of queries that have finished executing.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_query_executor_queries_finished{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Database: Number of Measurements",
   "type": "singlestat",
   "description": "The current number of measurements in the specified database.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_database_num_measurements{job=~\"$job\"})",
     "legendFormat": "{{job}} ({{database}})"
    }
   ]
  },
  {
   "title": "Database: Number of Series",
   "type": "singlestat",
   "description": "The current series cardinality of the specified database.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_database_num_series{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "HTTPD: Requests Active",
   "type": "graph",
   "description": "The number of currently active requests.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(influxdb_httpd_req_active{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": " HTTPD: Request Duration",
   "type": "graph",
   "description": "The duration (wall time), in nanoseconds, spent inside HTTP requests.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(influxdb_httpd_req_duration_ns{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Write Requests",
   "type": "graph",
   "description": "The number of write requests served using the HTTP /write endpoint.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(influxdb_httpd_write_req{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Write Request Duration",
   "type": "graph",
   "description": "The duration (wall time), in nanoseconds, of write requests served using the /write HTTP endpoint.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(influxdb_httpd_write_req_duration_ns{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Server Errors",
   "type": "singlestat",
   "description": "The number of HTTP responses due to server errors.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_httpd_server_error{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Client Errors",
   "type": "singlestat",
   "description": "The number of HTTP responses due to client errors, with a 4XX HTTP status code.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_httpd_client_error{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Points Written Failed",
   "type": "singlestat",
   "description": "The number of points accepted by the HTTP /write endpoint, but unable to be persisted.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_httpd_points_written_fail{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Points Written Dropped",
   "type": "singlestat",
   "description": "The number of points dropped by the storage engine.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_httpd_points_written_dropped{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTPD: Recovered Panics",
   "type": "singlestat",
   "description": "The total number of panics recovered by the HTTP handler.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_httpd_recovered_panics{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Query Executor: Recovered Panics",
   "type": "singlestat",
   "description": "The number of panics recovered by the Query Executor.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_query_executor_recovered_panics{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Shard: Write Points Dropped",
   "type": "singlestat",
   "description": "The sum of total number of requests to write points dropped from a write across all shards",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_shard_write_points_dropped{job=~\"$job\"})\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Shard: Write Point Errors",
   "type": "singlestat",
   "description": "The sum of total number of requests to write points that failed to be written due to errors.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_shard_write_points_err{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Shard: Failed Write Requests",
   "type": "singlestat",
   "description": "The maximum number of failed write requests that failed due to errors in a particular shard.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_shard_write_req_err{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Subscriber: Failed Subscriptions",
   "type": "singlestat",
   "description": "The number of subscriptions that failed to be created.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_subscriber_create_failures{job=~\"$job\"}[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TSM1 Cache: Writes Dropped",
   "type": "singlestat",
   "description": "The total number of writes dropped due to timeouts across all shards.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_cache_write_dropped{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TSM1 Cache: Failed Writes",
   "type": "singlestat",
   "description": "The total number of writes that failed across all shards.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_cache_write_err{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TSM1 Engine: Cache Compaction Error",
   "type": "singlestat",
   "description": "The number of cache compactions that have failed due to errors. across different shards for different databases",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_engine_cache_compaction_err{job=~\"$job\"})",
     "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
    }
   ]
  },
  {
   "title": "TSM1 Engine: Full Compaction Errors",
   "type": "singlestat",
   "description": "The total number of TSM full compactions that have failed due to errors across different shards for different databases",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_engine_tsm_full_compaction_err{job=~\"$job\"})",
     "legendFormat": "{{job}} {{database}} shard:{{id}}"
    }
   ]
  },
  {
   "title": "TSM1 WAL: Failed Writes",
   "type": "singlestat",
   "description": "The number of writes that failed due to errors on each shard.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(influxdb_tsm1_wal_write_err{job=~\"$job\"})",
     "legendFormat": "job:{{job}}, database: {{database}} (shard:{{id}})"
    }
   ]
  },
  {
   "title": "Write: Failed Writes (Batches)",
   "type": "singlestat",
   "description": "The total number of batches of points that failed to be sent to the subscription dispatcher for a particular instance.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_write_sub_write_drop[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Write: Dropped Writes",
   "type": "singlestat",
   "description": "The total number of write requests for points that have been dropped due to timestamps not matching any existing retention policies.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_write_write_drop[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Write: Write Timeouts",
   "type": "singlestat",
   "description": "The total number of write requests that failed to complete within the default write timeout duration. This could indicate severely reduced or contentious disk I/O or a congested network to a remote node.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_write_write_timeout[$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Write: Write Errors (Batches)",
   "type": "singlestat",
   "description": "The total number of batches of points that were not successfully written, due to a failure to write to a local or remote shard.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(influxdb_write_write_error [$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Continuous Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Ok",
     "type": "graph",
     "description": "Displays the total number of continuous queries that executed successfully.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_cq_query_ok{job=~\"$job\"}[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Query Failed",
     "type": "graph",
     "description": "Displays the total number of continuous queries that executed but failed",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_cq_query_fail{job=~\"$job\"}[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Measurements",
     "type": "graph",
     "description": "The current number of measurements in the specified database.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "influxdb_database_num_measurements{job=~\"$job\"}",
       "legendFormat": "{{job}} ({{database}})"
      }
     ]
    },
    {
     "title": "Number of Series",
     "type": "graph",
     "description": "The current series cardinality of the specified database.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "influxdb_database_num_series{job=~\"$job\"}",
       "legendFormat": "{{job}} ({{database}})"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTPD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Authentication Failed",
     "type": "graph",
     "description": "The number of HTTP requests that were aborted due to authentication being required, but not supplied or incorrect.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_auth_fail{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Client Errors",
     "type": "graph",
     "description": "The number of HTTP responses due to client errors, with a 4XX HTTP status code.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_client_error{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Flux Query Requests",
     "type": "graph",
     "description": "The number of Flux query requests served.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_flux_query_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Flux Query Request Duration",
     "type": "graph",
     "description": "Displays the duration, in nanoseconds, of the top 1% of HTTP write requests.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "rate(influxdb_httpd_flux_query_req_duration_ns{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Ping Requests",
     "type": "graph",
     "description": "The number of times InfluxDB HTTP server served the /ping HTTP endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_ping_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Points Written Dropped",
     "type": "graph",
     "description": "The number of points dropped by the storage engine.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_points_written_dropped{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Points Written Failed",
     "type": "graph",
     "description": "The number of points accepted by the HTTP /write endpoint, but unable to be persisted.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_points_written_fail{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Points Written OK",
     "type": "graph",
     "description": "The number of points accepted by the HTTP /write endpoint and persisted successfully.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_points_written_o_k{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Prometheus Read Requests",
     "type": "graph",
     "description": "The number of read requests to the Prometheus /read endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_prom_read_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Prometheus Write Requests",
     "type": "graph",
     "description": "The number of write requests to the Prometheus /write endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_prom_write_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Query Requests",
     "type": "graph",
     "description": "The total number of query requests.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_query_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Query Request Duration",
     "type": "graph",
     "description": "Displays the duration, in nanoseconds, of the top 1% of HTTP requests.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "rate(influxdb_httpd_query_req_duration_ns{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Query Response Bytes",
     "type": "graph",
     "description": "The total number of bytes returned in query responses.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_query_resp_bytes{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Recovered Panics",
     "type": "graph",
     "description": "The total number of panics recovered by the HTTP handler.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_recovered_panics{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Requests Served",
     "type": "graph",
     "description": "The total number of HTTP requests served.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Requests Active",
     "type": "graph",
     "description": "The number of currently active requests.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_req_active{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": " Request Duration",
     "type": "graph",
     "description": "The duration (wall time), in nanoseconds, spent inside HTTP requests.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "rate(influxdb_httpd_req_duration_ns{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Server Errors",
     "type": "graph",
     "description": "The number of HTTP responses due to server errors.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_server_error{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Status Requests",
     "type": "graph",
     "description": "The number of status requests served using the HTTP /status endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_status_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Requests",
     "type": "graph",
     "description": "The number of write requests served using the HTTP /write endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_write_req{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Requests Active",
     "type": "graph",
     "description": "The total number of currently active write requests.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "influxdb_httpd_write_req_active{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Request Bytes",
     "type": "graph",
     "description": "The total number of bytes of line protocol data received by write requests, using the HTTP /write endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_httpd_write_req_bytes{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Request Duration",
     "type": "graph",
     "description": "The duration (wall time), in nanoseconds, of write requests served using the /write HTTP endpoint.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "rate(influxdb_httpd_write_req_duration_ns{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Executor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Queries",
     "type": "graph",
     "description": "The number of active queries currently being handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_query_executor_queries_active{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Executed Queries",
     "type": "graph",
     "description": "The number of queries executed (started).",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_query_executor_queries_executed{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Finished Queries",
     "type": "graph",
     "description": "The number of queries that have finished executing.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_query_executor_queries_finished{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Query Duration",
     "type": "graph",
     "description": "The duration (wall time), in nanoseconds, of every query executed.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_query_executor_query_duration_ns{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Recovered Panics",
     "type": "graph",
     "description": "The number of panics recovered by the Query Executor.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_query_executor_recovered_panics{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Bytes",
     "type": "graph",
     "description": "The currently allocated number of bytes of heap objects.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_alloc{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Freed Heap Objects",
     "type": "graph",
     "description": "The cumulative number of freed (live) heap objects.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_frees{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap Allocated Bytes",
     "type": "graph",
     "description": "The size, in bytes, of all heap objects.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_heap_alloc{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap In-Use Bytes",
     "type": "graph",
     "description": "The number of bytes in in-use spans.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_heap_in_use{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap Idle Bytes",
     "type": "graph",
     "description": "The number of bytes of idle heap objects.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_heap_idle{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap Released Bytes",
     "type": "graph",
     "description": "The number of bytes of physical memory returned to the OS.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_heap_released{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap Objects",
     "type": "graph",
     "description": "The number of allocated heap objects.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_heap_objects{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Heap System Bytes",
     "type": "graph",
     "description": "The number of bytes of heap memory obtained from the OS.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_heap_sys{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Lookups",
     "type": "graph",
     "description": "The number of pointer lookups performed by the runtime.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_lookups{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Mallocs",
     "type": "graph",
     "description": "The total number of heap objects allocated.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_mallocs{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Number of Garbage Collections",
     "type": "graph",
     "description": "The number of completed GC (garbage collection) cycles.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_num_g_c{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Number of Go Routines",
     "type": "graph",
     "description": "The total number of Go routines.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_num_goroutine{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Pause Duration Garbage Collection",
     "type": "graph",
     "description": "The total duration, in nanoseconds, of total GC (garbage collection) pauses.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_pause_total_ns{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "System Bytes",
     "type": "graph",
     "description": "The total number of bytes of memory obtained from the OS.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "influxdb_runtime_sys{job=~\"$job\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Total Heap Allocatation Bytes",
     "type": "graph",
     "description": "The total number of bytes allocated for heap objects.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "increase(influxdb_runtime_total_alloc{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Disk Bytes",
     "type": "graph",
     "description": "The size, in bytes, of the top shard (among all those are present), including the size of the data directory and the WAL directory. ",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_shard_disk_bytes{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Fields Created",
     "type": "graph",
     "description": "The highest number of fields created. The panel shows the shard in which maximum number of fields are created.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_shard_fields_create{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Series Created",
     "type": "graph",
     "description": "Then number of series created.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum( influxdb_shard_series_create{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Bytes Written",
     "type": "graph",
     "description": "The maximum number of bytes written to a particular shard.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_shard_write_bytes{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Write Points Dropped",
     "type": "graph",
     "description": "The sum of total number of requests to write points dropped from a write across all shards",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(scalar(sum(floor(sum(count(influxdb_shard_write_points_dropped{job=~\"$job\"}) / 100) * 10) or vector(0))),influxdb_shard_write_points_dropped{job=~\"$job\"}) by (database)\r\n",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Write Point Errors",
     "type": "graph",
     "description": "The sum of total number of requests to write points that failed to be written due to errors.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,influxdb_shard_write_points_err{job=~\"$job\"}) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Write Points Successful",
     "type": "graph",
     "description": "The maximum number of points written successfully on a particular shard.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_shard_write_points_ok{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Total Write Requests",
     "type": "graph",
     "description": "The maximum number of write requests in a shard.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_shard_write_req{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Failed Write Requests",
     "type": "graph",
     "description": "The maximum number of failed write requests that failed due to errors in a particular shard.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,influxdb_shard_write_req_err{job=~\"$job\"}) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Successful Write Requests",
     "type": "graph",
     "description": "The highest total number of successful write requests on a shard.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_shard_write_points_ok{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriber",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Writes",
     "type": "graph",
     "description": "The total number of points that were successfully written to subscribers.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(influxdb_subscriber_points_written{job=~\"$job\"}[$__interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Failed Subscriptions",
     "type": "graph",
     "description": "The number of subscriptions that failed to be created.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(influxdb_subscriber_create_failures{job=~\"$job\"}[$__interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Failed Writes",
     "type": "graph",
     "description": "The total number of batches that failed to be written to subscribers.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(influxdb_subscriber_write_failures{job=~\"$job\"}[$__interval])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSM1 Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Cache Age",
     "type": "table",
     "description": "The duration, in milliseconds, since the cache was last snapshotted at sample time. This statistic indicates how busy the cache is. Large numbers indicate a cache which is idle with respect to writes.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_cache_cache_age_ms{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Active Snapshots",
     "type": "table",
     "description": "The current level (number) of active snapshots. Should be between 0 and 1.  A system experiencing transient write errors might expect to see this number rise.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_cache_snapshot_count{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top On-disk Snapshot Size",
     "type": "table",
     "description": "The current size, in bytes, of on-disk snapshots of the top three shards.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_cache_disk_bytes{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top In-Memory Cache Size",
     "type": "table",
     "description": "The current size, in bytes, of in-memory cache of the top two shards.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_cache_mem_bytes{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Shard Group Cached",
     "type": "graph",
     "description": "The total number of bytes that have been written into snapshots grouped into shards. The graph shows top one shard.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1, increase(influxdb_tsm1_cache_cached_bytes{job=~\"$job\"}[$__interval]))",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Commit Lock Duration",
     "type": "graph",
     "description": "The duration, in milliseconds, that the commit lock is held while compacting snapshots for the top three shards.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_cache_w_a_l_compaction_time_ms{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Writes Dropped",
     "type": "graph",
     "description": "The total number of writes dropped due to timeouts across all shards.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,influxdb_tsm1_cache_write_dropped{job=~\"$job\"}) by (database,job)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Failed Writes",
     "type": "graph",
     "description": "The total number of writes that failed across all shards.",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,influxdb_tsm1_cache_write_err{job=~\"$job\"}) by (job,database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Successful Writes",
     "type": "graph",
     "description": "The total number of successful writes across all shards.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_cache_write_ok{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSM1 Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Cache Compaction Duration",
     "type": "graph",
     "description": "The time, spent in cache compactions across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk(scalar(sum(floor(sum(count(influxdb_tsm1_engine_cache_compaction_duration) / 100) * 10) or vector(0))),influxdb_tsm1_engine_cache_compaction_duration) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Active Cache Compactions",
     "type": "graph",
     "description": "The total number of cache compactions that are actively running across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_cache_compactions_active{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Pending Full Compactions",
     "type": "graph",
     "description": "The current number of pending TMS Full compactions across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_full_compaction_queue{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Full Compaction Duration",
     "type": "graph",
     "description": "The duration (wall time), in nanoseconds, spent in full compactions across all shards and databases.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_full_compaction_duration{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Active Full Compactions",
     "type": "graph",
     "description": "The number of TSM full compactions currently running across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_full_compactions_active{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Pending TSM Optimize Compactions",
     "type": "graph",
     "description": "The current number of pending TSM optimize compactions across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " topk(1,sum(influxdb_tsm1_engine_tsm_optimize_compaction_queue{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Cache Compaction Error",
     "type": "graph",
     "description": "The number of cache compactions that have failed due to errors. across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " topk(1,sum(influxdb_tsm1_engine_cache_compaction_err{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Completed Full Compactions",
     "type": "graph",
     "description": "The total number of TSM full compactions that have ever run across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_full_compactions{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Full Compaction Duration",
     "type": "graph",
     "description": "The duration (wall time), in nanoseconds, spent in full compactions across all shards and databases.",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_optimize_compaction_duration{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Completed TSM Optimize Compactions",
     "type": "graph",
     "description": "The total number of TSM optimize compactions that have ever run across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_optimize_compactions{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Cache Compactions",
     "type": "graph",
     "description": "The total number of cache compactions that have ever run across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_cache_compactions{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Full Compaction Errors",
     "type": "graph",
     "description": "The total number of TSM full compactions that have failed due to errors across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_full_compaction_err{job=~\"$job\"} ) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Failed TSM Optimize Compactions",
     "type": "graph",
     "description": "The total number of TSM optimize compactions that have failed due to errors across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_optimize_compaction_err{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Active TSM Optimize Compactions",
     "type": "graph",
     "description": "The number of TSM optimize compactions that are currently running across different shards for different databases",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_engine_tsm_optimize_compactions_active{job=~\"$job\"} ) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSM1 Filestore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Disk Usage",
     "type": "graph",
     "description": "The size, in bytes, of disk usage by the TSM file store across different shards.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_filestore_disk_bytes{job=~\"$job\"} ) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Number of Files",
     "type": "graph",
     "description": "The total number of files in the TSM file store across different shards.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_filestore_num_files{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TSM1 WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Current Segment Disk Size",
     "type": "graph",
     "description": "The current size, in bytes, of the segment disk for the top two shards.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_wal_current_segment_disk_bytes{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Failed Writes",
     "type": "graph",
     "description": "The number of writes that failed due to errors on each shard.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_wal_write_err{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Successful Writes",
     "type": "graph",
     "description": "The number of writes that succeeded on each shard.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_wal_write_ok{job=~\"$job\"}) by (job,database,id)) by (database)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    },
    {
     "title": "Top Old Segment Disk Size",
     "type": "graph",
     "description": "The size, in bytes, of the segment disk.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(1,sum(influxdb_tsm1_wal_old_segments_disk_bytes{job=~\"$job\"}) by (job,database,id)) by (job)",
       "legendFormat": "{{job}} ({{database}}) shard:{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Point Requests",
     "type": "graph",
     "description": "The total number of every point requested to be written to this instance.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_point_req[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Failed Writes (Batches)",
     "type": "graph",
     "description": "The total number of batches of points that failed to be sent to the subscription dispatcher for a particular instance.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_sub_write_drop[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Dropped Writes",
     "type": "graph",
     "description": "The total number of write requests for points that have been dropped due to timestamps not matching any existing retention policies.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_write_drop[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Successful Writes (Batches)",
     "type": "graph",
     "description": "The total number of batches of points that were successfully sent to the subscription dispatcher.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_sub_write_ok[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Batch Point Requests",
     "type": "graph",
     "description": "The total number of batches of points requested to be written to this instance.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_req[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write OK (Batches)",
     "type": "graph",
     "description": "The total number of batches of points written at the requested consistency level.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_write_ok [$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Timeouts",
     "type": "graph",
     "description": "The total number of write requests that failed to complete within the default write timeout duration. This could indicate severely reduced or contentious disk I/O or a congested network to a remote node.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_write_timeout[$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Write Errors (Batches)",
     "type": "graph",
     "description": "The total number of batches of points that were not successfully written, due to a failure to write to a local or remote shard.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (task,instance) (increase(influxdb_write_write_error [$__interval]))",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}